# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_pass
      POSTGRES_DB: data
  admin:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
  migrate:
    image: flyway/flyway:latest
    command: -locations=filesystem:/flyway/sql -connectRetries=60 migrate
    volumes:
      - $PWD/migration:/flyway/sql
    env_file:
      - .env
    depends_on:
      - db